### 套件安裝

In [1]:
import tensorflow 
import keras

In [2]:
print(tensorflow.__version__)

2.10.1


In [3]:
print(keras.__version__)

2.10.0


In [4]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17324420278314933962
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 1470965147
locality {
  bus_id: 1
  links {
  }
}
incarnation: 15462192302575846688
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1"
xla_global_id: 416903419
]


### CNN基本概念

In [6]:
import numpy as np

In [7]:
u = np.zeros([3, 6], dtype = np.uint8)
d = np.ones([3, 6], dtype = np.uint8)*255
OuO1 = np.append(u, d, axis=0)
print(OuO1)

[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [255 255 255 255 255 255]
 [255 255 255 255 255 255]
 [255 255 255 255 255 255]]


In [8]:
u = np.zeros([6, 3], dtype = np.uint8)
d = np.ones([6, 3], dtype = np.uint8)*255
OuO2 = np.append(u, d, axis=1)
print(OuO2)

[[  0   0   0 255 255 255]
 [  0   0   0 255 255 255]
 [  0   0   0 255 255 255]
 [  0   0   0 255 255 255]
 [  0   0   0 255 255 255]
 [  0   0   0 255 255 255]]


In [9]:
OuO3 = np.array([[0, 0, 0, 255, 255], 
                 [0, 0, 255, 255, 255], 
                 [0, 255, 255, 255, 255],
                 [255, 255, 255, 255, 255],
                 [255, 255, 255, 255, 255]])

In [10]:
mask_v = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
mask_h = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])
print(mask_v)
print(mask_h)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


In [11]:
def convolution2d(image, kernel, bias):
    m, n = kernel.shape
    if (m == n):
        y, x = image.shape
        y = y - m + 1
        x = x - m + 1
        new_image = np.zeros((y,x))
        for i in range(y):
            for j in range(x):
                new_image[i][j] = np.sum(image[i:i+m, j:j+m]*kernel) + bias
    return new_image
# from https://stackoverflow.com/questions/2448015/2d-convolution-using-python-and-numpy

In [12]:
convolution2d(image=OuO1, kernel=mask_v, bias=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
convolution2d(image=OuO1, kernel=mask_h, bias=0)

array([[  0.,   0.,   0.,   0.],
       [765., 765., 765., 765.],
       [765., 765., 765., 765.],
       [  0.,   0.,   0.,   0.]])

In [14]:
convolution2d(image=OuO2, kernel=mask_v, bias=0)

array([[  0., 765., 765.,   0.],
       [  0., 765., 765.,   0.],
       [  0., 765., 765.,   0.],
       [  0., 765., 765.,   0.]])

In [15]:
convolution2d(image=OuO2, kernel=mask_h, bias=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
convolution2d(image=OuO3, kernel=mask_v, bias=0)

array([[510., 510., 255.],
       [510., 255.,   0.],
       [255.,   0.,   0.]])

In [17]:
convolution2d(image=OuO3, kernel=mask_h, bias=0)

array([[510., 510., 255.],
       [510., 255.,   0.],
       [255.,   0.,   0.]])